inherit_from:
  - .bixby.yml

RSpec/DescribeClass:
  Exclude:
    - smoke_spec/deploy_spec.rb

Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'spec/**/*.rb'
    - 'smoke_spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - lib/camerata/taggable_app.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/camerata/taggable_app.rb

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'smoke_spec/**/*.rb'
