inherit_from:
  - .bixby.yml

RSpec/DescribeClass:
  Exclude:
    - smoke_spec/deploy_spec.rb

Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'spec/**/*.rb'
    - 'smoke_spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'smoke_spec/**/*.rb'

