# Place configuration unique to running in local docker here
version: '3'

services:
  solr:
    volumes:
      - ./solrdata:/var/solr/data/blacklight-core
    logging:
      driver: json-file
    env_file: ../yul-dc-solr/.env
    build:
      context: ../yul-dc-solr 
    command: bash -c 'precreate-core $${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

  db:
    build: ../yul-dc-postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    logging:
      driver: json-file

  management:
    image: 'yalelibraryit/dc-management:master'
    command: bash -c 'RAILS_ENV=development bundle exec rails server -b 0.0.0.0 -p 3001'
    build: "../yul-dc-management"
    env_file:
      - ../yul-dc-management/.env
      - ../yul-dc-management/.secrets
    environment:
      REGISTRY_URI: yalelibraryit/dc-blacklight
      REGISTRY_HOST: dockerhub.io
    volumes:
      - ../yul-dc-management:/home/app/webapp:rw

  iiif_manifest:
    image: yalelibraryit/yul-dc-iiif-manifest:master
    env_file: ../yul-dc-iiif-manifest/.env
    build: 
      context: ../yul-dc-iiif-manifest


  iiif_image:
    env_file: ../yul-dc-iiif-imageserver/.env
    build: ../yul-dc-iiif-imageserver 
    image: "yalelibraryit/dc-iiif-cantaloupe:master"

  blacklight:
    build: "../yul-dc-blacklight"
    image: 'yalelibraryit/dc-blacklight:master'
    env_file: ../yul-dc-blacklight/.env
    env_file: ../yul-dc-blacklight/.env.development
    command: bash -c 'RAILS_ENV=development bundle exec rails server -b 0.0.0.0'
    volumes:
      - ../yul-dc-blacklight/:/home/app/webapp
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_URL: http://solr:8983/solr/blacklight-core
      IIIF_MANIFESTS_BASE_URL: ${IIIF_MANIFESTS_BASE_URL}
      PASSENGER_APP_ENV: development
      REGISTRY_URI: yalelibraryit/dc-blacklight
      REGISTRY_HOST: dockerhub.io
    depends_on:
      - db
      - solr
      - iiif_manifest
      - management
