version: '3'

services:
  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION}
    ports:
      - '80:80'
    environment:
      IIIF_MANIFESTS_BASE_URL: http://localhost/manifests/
      IIIF_IMAGE_BASE_URL: http://localhost:8182/iiif


  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION}
    environment:
      S3CACHE_BUCKET_NAME: yale-image-samples/cantaloupe/cache #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME: yale-image-samples
      IIIF_IMAGE_VERSION:
    env_file:
      - .secrets
    ports:
      - "8182:8182"

  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_VERSION}
    command: bash -c "echo $$(date -u +%FT%TZ) > DEPLOYED_AT && sleep 30 && /sbin/my_init"
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_URL: http://solr:8983/solr/blacklight-core
      IIIF_MANIFESTS_BASE_URL: http://localhost/manifests/
      PASSENGER_APP_ENV: development
      HTTP_PASSWORD_PROTECT: 'true'
      BLACKLIGHT_VERSION:
    env_file:
      - .secrets
    ports:
      - "3000:3000"

  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    command: /bin/sh -c "cd /home/app/webapp && sleep 60 && SOLR_CORE=blacklight-core METADATA_SOURCE=ladybird bundle exec rake yale:index_fixture_data && /sbin/my_init"
    env_file:
      - .secrets
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_BASE_URL: http://solr:8983/solr
      SOLR_CORE: blacklight-core
      PASSENGER_APP_ENV: development
    ports:
      - "3001:3001"
