services:
  iiif_manifest:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest

  solr:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: solr

  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image
    environment:
      IIIF_MANIFESTS_BASE_URL: /manifests/

  db:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: db_blacklight

  blacklight:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
    environment:
      SOLR_URL: http://localhost:8983/solr/blacklight-core
      POSTGRES_HOST: localhost

  # management:
  #   logging:
  #     driver: awslogs
  #     options:
  #       awslogs-group: ${CLUSTER_NAME}
  #       awslogs-region: ${AWS_DEFAULT_REGION}
  #       awslogs-stream-prefix: management
  # environment:
  #   SOLR_URL: http://localhost:8983/solr
  #   POSTGRES_HOST: localhost
