version: '3'

services:
  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION}
    ports:
      - '80:80'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_VERSION}
    environment:
      SOLR_CORE: blacklight-core
      SOLR_VERSION:
    ports:
      - "8983:8983"
    command: bash -c 'cp -rn /opt/config/ /var/solr/data/$${SOLR_CORE}/conf && touch /var/solr/data/$${SOLR_CORE}/core.properties && exec solr -f'
    volumes:
      - solr_efs:/var/solr/data/blacklight-core #this appears to not support variable expansion :/

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION}
    environment:
      S3CACHE_BUCKET_NAME: yale-image-samples/cantaloupe/cache #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME: yale-image-samples
      IIIF_IMAGE_VERSION:
    env_file:
      - .secrets
    ports:
      - "8182:8182"

  db:
    image: curationexperts/dc-postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_MULTIPLE_DATABASES: blacklight_yul_development,yul_dc_management_development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "psql_efs:/var/lib/postgresql/data"

  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_VERSION}
    command: bash -c "echo $$(date -u +%FT%TZ) > DEPLOYED_AT && sleep 30 && /sbin/my_init"
    environment:
      POSTGRES_DB: blacklight_yul_development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_URL: http://solr:8983/solr/blacklight-core
      IIIF_MANIFESTS_BASE_URL: http://localhost/manifests/
      PASSENGER_APP_ENV: development
      HTTP_PASSWORD_PROTECT: 'true'
      BLACKLIGHT_VERSION:
    env_file:
      - .secrets
    ports:
      - "3000:3000"

  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    command: /bin/sh -c "cd /home/app/webapp && sleep 30 && /sbin/my_init" #the reindex job should only be run once, preferably from inside the mgmt app itself
    env_file:
      - .secrets
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SOLR_BASE_URL: http://solr:8983/solr
      SOLR_CORE: blacklight-core
      PASSENGER_APP_ENV: development
    ports:
      - "3001:3001"

volumes:
  solr_efs:
  psql_efs:
