version: '2.1'
services:

  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_TAG}
    command: /bin/sh -c "cd /home/app/webapp && sleep 10 && rake yale:load_voyager_sample_data && /sbin/my_init"
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - solr
      - db
      - iiif_image
      - iiif_manifest

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${CANTALOUPE_TAG}
    env_file:
      - .env
    ports:
      - '8182:8182'

  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${MANIFEST_TAG}
    env_file:
      - .env
    ports:
      - '80:80'

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG}
    ports:
      - '8983:8983'
    volumes:
      - solr:/var/solr/data
    env_file:
      - .env
    command: bash -c 'precreate-core ${SOLR_CORE} /opt/config; precreate-core ${SOLR_TEST_CORE} /opt/config; exec solr -f'

volumes:
  postgres:
  solr:
