version: '2.1'
services:

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG}
    ports:
      - '8983:8983'
    volumes:
      - solr:/var/solr/data
    env_file:
      - .env
    command: bash -c 'precreate-core blacklight-development /opt/config; precreate-core blacklight-test /opt/config; exec solr -f'

volumes:
  postgres:
  solr:
