services:
  iiif_manifest:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest

  solr:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: solr

  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image

  db_blacklight:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: db_blacklight

  # db_management:
  #   ports:
  #     - "5434:5434"
  #   logging:
  #     driver: awslogs
  #     options:
  #       awslogs-group: ${CLUSTER_NAME}
  #       awslogs-region: ${AWS_DEFAULT_REGION}
  #       awslogs-stream-prefix: db_management

  blacklight:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
   environment:
     POSTGRES_DB: blacklight_yul_development
     POSTGRES_HOST: db_blacklight
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
     SOLR_URL: http://localhost:8983/solr/blacklight-core
     IIIF_MANIFESTS_BASE_URL: /manifests/
     PASSENGER_APP_ENV: development
     BLACKLIGHT_VERSION:


  # management:
  #   logging:
  #     driver: awslogs
  #     options:
  #       awslogs-group: ${CLUSTER_NAME}
  #       awslogs-region: ${AWS_DEFAULT_REGION}
  #       awslogs-stream-prefix: management
