# Place configuration unique to running on ECS here
services:
  iiif_manifest:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest

  solr:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: solr

  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image

  db:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: db_blacklight

  blacklight:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
    environment:
      SOLR_URL: http://localhost:8983/solr/blacklight-core
      POSTGRES_HOST: localhost
      IIIF_MANIFESTS_BASE_URL: /manifests/
      PASSENGER_APP_ENV: production

  management:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management
    environment:
      SOLR_BASE_URL: http://localhost:8983/solr
      POSTGRES_HOST: localhost
      PASSENGER_APP_ENV: production


