# Place configuration unique to running in local docker here
version: '3'

services:

  solr:
    volumes:
      - ./solrdata:/var/solr/data/blacklight-core
  db:
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  blacklight:
    depends_on:
      - db
      - solr
      - iiif_manifest
      - management
    volumes:
      - ../yul-dc-blacklight:/home/app/webapp
