# Place configuration unique to running on ECS here
services:
  iiif_manifest:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest
    environment:
      IIIF_MANIFESTS_BASE_URL: 'https://$$host/manifests/'
      IIIF_IMAGE_BASE_URL: 'https://$$host/iiif'

  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image
    environment:
      HONEYBADGER_API_KEY_IMAGESERVER: dfb3b5d2

  blacklight:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
    environment:
      SOLR_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr/blacklight-core
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
      IIIF_MANIFESTS_BASE_URL: /manifests/
      HONEYBADGER_API_KEY: 1979eb78
      HONEYBADGER_API_KEY_BLACKLIGHT: 1979eb78

  management:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management
    environment:
      SOLR_BASE_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
      HONEYBADGER_API_KEY: 057e1879
      HONEYBADGER_API_KEY_MANAGEMENT: 057e1879
