version: '2.1'
services:

  camerata:
    image: '${REGISTRY_HOST}${REGISTRY_URI}:${CAMERATA_TAG}'
    env_file:
      - .env
      - .env.development
    build:
      context: .

  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_TAG}
    command: /bin/sh -c "cd /home/app/webapp && sleep 10 && rake yale:load_voyager_sample_data && /sbin/my_init"
    env_file:
      - .env
      - .env.development
    ports:
      - '3000:3000'
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    depends_on:
      - solr
      - db
      - iiif_image
      - iiif_manifest

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${CANTALOUPE_TAG}
    env_file:
      - .env
    ports:
      - '8182:8182'

  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${MANIFEST_TAG}
    env_file:
      - .env
    ports:
      - '80:80'

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG}
    ports:
      - '8983:8983'
    volumes:
      - solr:/var/solr/data
    env_file:
      - .env
    command: bash -c 'precreate-core blacklight-development /opt/config; precreate-core blacklight-test /opt/config; exec solr -f'

volumes:
  postgres:
  solr:
