version: '3'
services:
  solr:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: solr
    image: yalelibraryit/dc-solr:${SOLR_VERSION}
    environment:
      SOLR_CORE: blacklight-core
      SOLR_VERSION:
    ports:
      - "8983:8983"
    command: bash -c 'cp -rn /opt/config/ /var/solr/data/$${SOLR_CORE}/conf && touch /var/solr/data/$${SOLR_CORE}/core.properties && exec solr -f'
    volumes:
      - solr_efs:/var/solr/data/blacklight-core #this appears to not support variable expansion :/

volumes:
  solr_efs:
