commands:
  docker-tag:
    description: "Add a new tag to a docker image that has already been pulled"
    parameters:
      from_tag:
        type: string
        default: $CIRCLE_SHA1
      to_tag:
        type: string
        default: "master"
      image:
        type: string
    steps:
      - run: >
          docker tag <<parameters.image>>:<<parameters.from_tag>> <<parameters.image>>:<<parameters.to_tag>>
jobs:
  run-tests:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Bundler
          command: |
            gem install bundler -v 2.1.4 && bundle
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop --parallel
      - run:
          name: Setup Secrets
          command: |
            echo HTTP_USERNAME=test >> .secrets
            echo HTTP_PASSWORD=test >> .secrets
            echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> .secrets
            echo AWS_SECRET_KEY=${AWS_SECRET_KEY} >> .secrets
      - run:
          name: Docker Compose Up
          command: |
            set -x
            /bin/localup -d up
      - run:
          name: Wait for services to be fully up
          command: |
            wget --tries 10 --retry-connrefused http://localhost:8983/solr/
            wget --tries 10 --retry-connrefused http://test:test@localhost:3001
            wget --tries 10 --retry-connrefused http://test:test@localhost:3000
      - run:
          name: populate management index
          command: |
            docker-compose exec management bundle exec rake yale:index_fixture_data METADATA_SOURCE=ladybird
      - run:
          name: rspec
          command:  |
            bundle exec rspec
orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - run-tests:
          context: yul-dc
