commands:
  docker-tag:
    description: "Add a new tag to a docker image that has already been pulled"
    parameters:
      from_tag:
        type: string
        default: $CIRCLE_SHA1
      to_tag:
        type: string
        default: "main"
      image:
        type: string
    steps:
      - run: >
          docker tag <<parameters.image>>:<<parameters.from_tag>> <<parameters.image>>:<<parameters.to_tag>>
jobs:
  run-tests:
    docker:
      - image: cimg/ruby:3.2
    steps:
      - checkout
      - run:
          name: Bundler
          command: |
            gem install bundler -v 2.4.14 && bundle
      - run:
          name: aws-cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
            sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Set up aws
          command: |
            echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> .secrets
            echo AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} >> .secrets
            mkdir -p ~/.aws
            echo ${AWS_PROFILE_VALUE} | base64 -d > ~/.aws/credentials
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop --parallel
      - run:
          name: rspec
          command:  |
            bundle exec rspec
orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - run-tests:
          context: yul-dc
