commands:
  docker-tag:
    description: "Add a new tag to a docker image that has already been pulled"
    parameters:
      from_tag:
        type: string
        default: $CIRCLE_SHA1
      to_tag:
        type: string
        default: "master"
      image:
        type: string
    steps:
      - run: >
          docker tag <<parameters.image>>:<<parameters.from_tag>> <<parameters.image>>:<<parameters.to_tag>>
jobs:
  run-tests:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Bundler
          command: |
            gem install bundler -v 2.1.4 && bundle
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop --parallel
      - run:
          name: Setup Secrets
          command: |
            echo HTTP_USERNAME=test >> .secrets
            echo HTTP_PASSWORD=test >> .secrets
            echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> .secrets
            echo AWS_SECRET_KEY=${AWS_SECRET_KEY} >> .secrets
            mkdir -p ~/.aws
            echo ${AWS_PROFILE_VALUE} | base64 -d > ~/.aws/credentials
      - run:
          name: Docker Compose Up
          environment:
            RAILS_ENV: development
          command: |
            set -x
            ls -l
            bundle exec ./exe/camerata up -d
      - run:
          name: rspec
          command:  |
            bundle exec rspec
      - run:
          name: Wait for services to be fully up
          command: |
            wget --tries 10 --retry-connrefused http://localhost:8983/solr/
            wget --tries 10 --retry-connrefused http://test:test@localhost:3001
            wget --tries 10 --retry-connrefused http://test:test@localhost:3000
      - run:
          name: smoke specs
          command:  |
            bundle exec rspec smoke_spec
  deployed-smoke:
    docker:
      - image: circleci/ruby:2.6-stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Bundler
          command: |
            gem install bundler -v 2.1.4 && bundle
      - run:
          name: aws-cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
            sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Set up aws
          command: |
            echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> .secrets
            echo AWS_SECRET_KEY=${AWS_SECRET_KEY} >> .secrets
            mkdir -p ~/.aws
            echo ${AWS_PROFILE_VALUE} | base64 -d > ~/.aws/credentials
      - run:
          name: Deploy the main group of services
          command: |
            bundle exec cam deploy-main yul-deploy
      - run:
          name: smoke
          command: |
            YUL_DC_SERVER=collections-cd.curationexperts.com bundle exec cam smoke
orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - run-tests:
          context: yul-dc
  every-four-hours:
    triggers:
      - schedule:
          cron: "35 * * * *"
          filters:
            branches:
              only:
                - master
                - deploy-from-circle
    jobs:
      - deployed-smoke:
          context: yul-dc
