version: '3'
services:
  blacklight:
    <%- if in_blacklight? -%>
    build: .
    image: yalelibraryit/dc-blacklight:main
    <%- end -%>
    environment:
      BLACKLIGHT_BASE_URL: "http://localhost:3000"
      CLUSTER_NAME: "local"
      IIIF_IMAGE_BASE_URL: "http://localhost:8182/iiif"
      IIIF_IMAGE_INTERNAL_URL: "http://iiif_image:8182"
      IIIF_MANIFESTS_BASE_URL: "http://localhost/manifests/"
      IIIF_IMAGE_UPSTREAM_PORT: 3000
      IIIF_IMAGE_UPSTREAM_PROTO: http
      PDF_BASE_URL: "http://localhost/pdfs/"
      MANAGEMENT_HOST: "http://localhost:3001/management"
      PASSENGER_APP_ENV: development
      POSTGRES_DB: blacklight_yul_development
      SOLR_BASE_URL: ${SOLR_BASE_URL}
      SOLR_URL_WITH_CORE: ${SOLR_URL_WITH_CORE}
      SAMPLE_BUCKET: yul-dc-development-samples # manifests
      S3_SOURCE_BUCKET_NAME: yul-dc-dev-image-samples # image and ptiffs
      S3_DOWNLOAD_BUCKET_NAME: yul-dc-download-test # downloadable originals
      ACCESS_DOWNLOAD_BUCKET: yul-dc-development-samples
      OCR_DOWNLOAD_BUCKET: yul-dc-development-samples
      OWP_AUTH_TOKEN: ${OWP_AUTH_TOKEN}
      NGINX_RESOLVER: 127.0.0.11
    <%- if in_blacklight? -%>
    volumes:
      - .:/home/app/webapp:cached
      - blacklight_node_modules:/home/app/webapp/node_modules
      - blacklight_rails_cache:/home/app/webapp/tmp/cache
    <% end %>
    stdin_open: true
    tty: true
    depends_on:
      <%- unless without.match(/db/) -%>
      - db
      <%- end -%>
      <%- unless without.match(/solr/) -%>
      - solr
      <%- end -%>
      <%- unless without.match(/chrome/) -%>
      - chrome
      <%- end -%>
      <%- unless without.match(/iiif_image/) -%>
      - iiif_image
      <%- end -%>
      <%- unless without.match(/management/) -%>
      - management
      <%- end -%>
<%- if in_blacklight? -%>
volumes:
  blacklight_node_modules:
  blacklight_rails_cache:
<%- end -%>
