version: '3'
services:
  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_VERSION}
    environment:
      <%= app_urls %>
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      BLACKLIGHT_VERSION:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      S3_SOURCE_BUCKET_NAME:
      SAMPLE_BUCKET:
      SOLR_CORE: blacklight-core
      SOLR_URL: http://solr:8983/solr/blacklight-core
      YALE_NETWORK_IPS: ${YALE_NETWORK_IPS:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1}
    ports:
      - '3000:3000'
