version: '3'
services:
  blacklight:
    environment:
      AWS_ACCESS_KEY_ID: ${DEPLOY_KEY_ID}
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${DEPLOY_ACCESS_KEY}
      CLUSTER_NAME: ${CLUSTER_NAME}
      DYNATRACE_TOKEN: ${DYNATRACE_TOKEN}
      HONEYBADGER_API_KEY_BLACKLIGHT: ${HONEYBADGER_API_KEY_BLACKLIGHT}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      HTTP_PASSWORD_PROTECT: ${BLACKLIGHT_PASSWORD_PROTECT}
      HTTP_USERNAME: ${HTTP_USERNAME}
      IIIF_IMAGE_BASE_URL:
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SAMPLE_BUCKET:
      SOLR_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr/blacklight-core
      YALE_NETWORK_IPS: ${YALE_NETWORK_IPS:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1}
    command: bash -c "echo $$(date -u +%FT%TZ) > DEPLOYED_AT && sleep 30 && /sbin/my_init" # server
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
