version: '3'
services:
  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_VERSION}
    environment:
      <%= app_urls %>
      ACCESS_DOWNLOAD_BUCKET:
      ARCHIVES_SPACE_BASE_URL: ${ARCHIVES_SPACE_BASE_URL}
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      BLACKLIGHT_VERSION:
      FEATURE_FLAGS:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      MANAGEMENT_HOST:
      OCR_DOWNLOAD_BUCKET:
      OWP_AUTH_TOKEN: ${OWP_AUTH_TOKEN}
      S3_DOWNLOAD_BUCKET_NAME:
      S3_SOURCE_BUCKET_NAME:
      SAMPLE_BUCKET:
      SOLR_CORE: blacklight-core
      SOLR_BASE_URL: ${SOLR_BASE_URL}
      SOLR_URL_WITH_CORE: ${SOLR_URL_WITH_CORE}
      SSO_HOST: ${SSO_HOST}
      SSO_ID: ${SSO_ID}
      SSO_ISS: ${SSO_ISS}
      SSO_JWKS: ${SSO_JWKS}
      SSO_SECRET: ${SSO_SECRET}
      YALE_NETWORK_IPS: ${YALE_NETWORK_IPS:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1}
    ports:
      - '3000:3000'
