version: '3'
services:
  blacklight:
    environment:
      AWS_ACCESS_KEY_ID: ${DEPLOY_KEY_ID}
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${DEPLOY_ACCESS_KEY}
      CLUSTER_NAME: ${CLUSTER_NAME}
      DYNATRACE_TOKEN: ${DYNATRACE_TOKEN}
      TYPE: "blacklight"
      HONEYBADGER_API_KEY_BLACKLIGHT: ${HONEYBADGER_API_KEY_BLACKLIGHT}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      HTTP_PASSWORD_PROTECT: ${BLACKLIGHT_PASSWORD_PROTECT}
      HTTP_USERNAME: ${HTTP_USERNAME}
      IIIF_IMAGE_BASE_URL:
      IIIF_IMAGE_INTERNAL_URL: http://${CLUSTER_NAME}-images.${CLUSTER_NAME}:8182
      IIIF_IMAGE_UPSTREAM_PORT: 443
      IIIF_IMAGE_UPSTREAM_PROTO: https
      MANAGEMENT_HOST: http://${CLUSTER_NAME}-mgmt.${CLUSTER_NAME}:3001/management
      NGINX_RESOLVER: 10.5.68.2
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
      OWP_AUTH_TOKEN: ${OWP_AUTH_TOKEN}
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SAMPLE_BUCKET:
      SOLR_URL: ${SOLR_URL}
    command: bash -c "echo $$(date -u +%FT%TZ) > DEPLOYED_AT && sleep 30 && /sbin/my_init" # server
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: blacklight
