version: '3'
services:
  blacklight:
    image: yalelibraryit/dc-blacklight:${BLACKLIGHT_VERSION}
    environment:
      <%= app_urls %>
      ARCHIVES_SPACE_BASE_URL: ${ARCHIVES_SPACE_BASE_URL}
      MANAGEMENT_HOST:
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      BLACKLIGHT_VERSION:
      FEATURE_FLAGS:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      S3_SOURCE_BUCKET_NAME:
      S3_DOWNLOAD_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      SAMPLE_BUCKET:
      SOLR_CORE: blacklight-core
      SOLR_URL: http://solr:8983/solr/blacklight-core
      SSO_HOST: ${SSO_HOST}
      SSO_ID: ${SSO_ID}
      SSO_JWKS: ${SSO_JWKS}
      SSO_SECRET: ${SSO_SECRET}
      YALE_NETWORK_IPS: ${YALE_NETWORK_IPS:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1}
    ports:
      - '3000:3000'
