services:
  chrome:
    # password is 'secret'
    image: seleniarm/standalone-chromium:latest
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 3G
    environment:
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=
    ports:
      - 7900:7900
