version: '3'
services:
  db:
    image: yalelibraryit/dc-postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_VERSION:
    ports:
      - "5432:5432"
