version: '3'
services:
  db:
    command: /bin/bash -c '/boot.sh'
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      CLUSTER_NAME: ${CLUSTER_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: psql
    volumes:
      - "psql_efs:/var/lib/postgresql/data"

volumes:
  psql_efs:
