version: '3'
services:
  db:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db:
