version: '3'
services:
  iiif_image:
    environment:
      # Use AWS credentials for local development only
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}