version: '3'
services:
  iiif_manifest:
    environment:
      HONEYBADGER_API_KEY_MANIFEST: ${HONEYBADGER_API_KEY_MANIFEST}
      IIIF_IMAGE_BASE_URL:
      IIIF_MANIFESTS_BASE_URL:
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      POSTGRES_DB: iiif_manifest_yul_production
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    # This is a one-off workaround to create the needed database for iiif_manifest on an existing cluster.
    # To use, uncomment this line, deploy to create the database, then comment this line back out.
    # TODO: This should be an idempotent addition elsewhere 
    # command: 'bash -e bundle exec rake db:create'
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest
