version: '3'
services:
  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION}
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      CANTALOUPE_VERSION: 5.0.6
      S3CACHE_BUCKET_NAME: ${S3_SOURCE_BUCKET_NAME} #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME:
      S3_DOWNLOAD_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      HTTPS_KEY_PASSWORD: ${HTTPS_KEY_PASSWORD}
      HTTPS_KEY_STORE_PATH: ${HTTPS_KEY_STORE_PATH}
      IIIF_IMAGE_VERSION:
      IIIF_JAVA_OPTS:
    secrets:
      - HTTPS_KEY_STORE_PASSWORD
      - IIIF_IMAGE_KEYSTORE
    ports:
      - '8182:8182'
      - '8183:8183'
