version: '3'
services:
  iiif_image:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: yul-dc-dev-image-samples/cantaloupe/cache #NO TRAILING SLASH!
      SAMPLE_BUCKET: yul-dc-development-samples # manifests
      S3_SOURCE_BUCKET_NAME: yul-dc-dev-image-samples # image and ptiffs
      S3_DOWNLOAD_BUCKET_NAME: yul-dc-download-test # downloadable originals
      ACCESS_DOWNLOAD_BUCKET: yul-dc-development-samples
      OCR_DOWNLOAD_BUCKET: yul-dc-development-samples
      IIIF_IMAGE_VERSION:
      IIIF_JAVA_OPTS: -Xmx2g
