version: '3'
services:
  iiif_manifest:
    environment:
      IIIF_MANIFESTS_BASE_URL: 'https://$$host/manifests/'
      IIIF_IMAGE_BASE_URL: 'https://$$host/iiif'
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_manifest
