version: '3'
services:
  iiif_image:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: yul-dc-dev-image-samples/cantaloupe/cache #NO TRAILING SLASH!
      SAMPLE_BUCKET: yul-dc-development-samples # manifests
      S3_SOURCE_BUCKET_NAME: yul-dc-dev-image-samples # image and ptiffs
      IIIF_IMAGE_VERSION:
