version: '3'
services:
  iiif_image:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: yul-dc-dev-images/cantaloupe/cache #NO TRAILING SLASH!
      SAMPLE_BUCKET: yul-dc-test-manifests # manifests
      S3_SOURCE_BUCKET_NAME: yul-dc-dev-images # image and ptiffs
      IIIF_IMAGE_VERSION:
      LD_PRELOAD: ""
