version: '3'
services:
  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image
    environment:
      HONEYBADGER_API_KEY_IMAGESERVER:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: ${S3_SOURCE_BUCKET_NAME}/cantaloupe/cache #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME:
      IIIF_IMAGE_VERSION:
