services:
  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION}
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      CANTALOUPE_VERSION: 5.0.6
      S3CACHE_BUCKET_NAME: ${S3_SOURCE_BUCKET_NAME} #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME:
      S3_DOWNLOAD_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      IIIF_IMAGE_VERSION:
      IIIF_JAVA_OPTS:
    ports:
      - '8182:8182'
