version: '3'
services:
  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION:-latest}
    environment:
      S3CACHE_BUCKET_NAME: ${S3_SOURCE_BUCKET_NAME}/cantaloupe/cache #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME:
      IIIF_IMAGE_VERSION:
    ports:
      - '8182:8182'
