version: '3'
services:
  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image
    environment:
      HONEYBADGER_API_KEY_IMAGESERVER:
