version: '3'
services:
  iiif_image:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: iiif_image
    environment:
      HONEYBADGER_API_KEY_IMAGESERVER:
      AWS_ACCESS_KEY_ID: ${DEPLOY_KEY_ID}
      AWS_SECRET_KEY: ${DEPLOY_ACCESS_KEY}
      DYNATRACE_TOKEN: ${DYNATRACE_TOKEN}
      CLUSTER_NAME: ${CLUSTER_NAME}
      JAVA_OPTS: -XX:MaxRAMPercentage=80.0
