version: '3'
services:
  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:${IIIF_IMAGE_VERSION:-latest}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3CACHE_BUCKET_NAME: ${S3_SOURCE_BUCKET_NAME}/cantaloupe/cache #NO TRAILING SLASH!
      S3_SOURCE_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      IIIF_IMAGE_VERSION:
      IIIF_JAVA_OPTS:
    ports:
      - '8182:8182'
