version: '3'
services:
  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION:-latest}
    ports:
      - '80:80'
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      IIIF_MANIFEST_VERSION:
      PASSENGER_APP_ENV: development # development
      POSTGRES_DB: iiif_manifest_yul_development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_RELATIVE_URL_ROOT: /manifests
      SAMPLE_BUCKET: yul-development-samples
