version: '3'
services:
  iiif_manifest:
    <%- if in_manifest? -%>
    build: .
    image: yalelibraryit/dc-iiif-manifest:${IIIF_MANIFEST_VERSION:-master}
    <%- end -%>
    environment:
      # Use AWS credentials for local development only
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      PASSENGER_APP_ENV: development
      POSTGRES_MULTIPLE_DATABASES: iiif_manifest_yul_development
      SAMPLE_BUCKET: yul-dc-development-samples
    <%- if in_manifest? -%>
    volumes:
      - .:/home/app/webapp:cached
    <%- end -%>
    stdin_open: true
    tty: true
    <%- unless without.match(/db/) -%>
    depends_on:
      - db
    <%- end -%>
