version: '3'
services:
  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    command: /sbin/setuser app bash -l -c "bundle exec good_job start || bundle exec delayed_job_worker_pool config/delayed_job_pool.rb"
    environment:
      <%= app_urls %>
      ACCESS_PRIMARY_MOUNT: "s3" # The path to the mounted drive, or "S3"
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      FEATURE_FLAGS:
      GOOBI_MOUNT:
      GOOBI_SCAN_DIRECTORIES:
      METADATA_CLOUD_HOST:
      PRESERVICA_HOST:
      PRESERVICA_CREDENTIALS:
      PASSENGER_APP_ENV: development # development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_RELATIVE_URL_ROOT: /management
      S3_SOURCE_BUCKET_NAME:
      S3_DOWNLOAD_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      SAMPLE_BUCKET: yul-development-samples
      SOLR_BASE_URL: ${SOLR_BASE_URL}
      SOLR_URL_WITH_CORE: ${SOLR_URL_WITH_CORE}
      SOLR_CORE: blacklight-core
      VPN:
      MC_USER:
      MC_PW:
      # The management app needs the versions for all the applications for the dashboard
      IIIF_MANIFEST_VERSION:
      SOLR_VERSION:
      IIIF_IMAGE_VERSION:
      POSTGRES_VERSION:
      BLACKLIGHT_VERSION:
      MANAGEMENT_VERSION:
      CAMERATA_VERSION:
      WORKER_COUNT:
      WORKER_QUEUES:
