version: '3'
services:
  management:
    environment:
      AWS_ACCESS_KEY_ID: ${DEPLOY_KEY_ID}
      TYPE: "intensive"
      CLUSTER_NAME: ${CLUSTER_NAME}
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${DEPLOY_ACCESS_KEY}
      GOOBI_MOUNT:
      GOOBI_SCAN_DIRECTORIES:
      HTTP_USERNAME: ${HTTP_USERNAME}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      IIIF_IMAGE_BASE_URL:
      IIIF_MANIFESTS_BASE_URL:
      PDF_BASE_URL:
      MC_USER: ${MC_USER}
      MC_PW: ${MC_PW}
      METADATA_CLOUD_HOST:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HONEYBADGER_API_KEY_MANAGEMENT: ${HONEYBADGER_API_KEY_MANAGEMENT}
      POSTGRES_DB: management_yul_production
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      S3_SOURCE_BUCKET_NAME:
      S3_DOWNLOAD_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      SAMPLE_BUCKET:
      SOLR_BASE_URL: ${SOLR_BASE_URL}
      SOLR_URL_WITH_CORE: ${SOLR_URL_WITH_CORE}
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: intensive_worker
