version: '3'
services:
  management:
    environment:
      HTTP_USERNAME: ${HTTP_USERNAME}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      IIIF_IMAGE_BASE_URL: 'https://collections-test.library.yale.edu/iiif'
      IIIF_MANIFESTS_BASE_URL: 'https://collections-test.library.yale.edu/manifests'
      MC_USER: ${MC_USER}
      MC_PW: ${MC_PW}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HONEYBADGER_API_KEY_MANAGEMENT: ${HONEYBADGER_API_KEY_MANAGEMENT}
      POSTGRES_DB: management_yul_production
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      S3_SOURCE_BUCKET_NAME:
      SAMPLE_BUCKET:
      SOLR_BASE_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management
  management_worker:
    environment:
      HTTP_USERNAME: ${HTTP_USERNAME}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      IIIF_IMAGE_BASE_URL: 'https://collections-demo.library.yale.edu/iiif'
      IIIF_MANIFESTS_BASE_URL: 'https://collections-demo.library.yale.edu/manifests'
      MC_USER: ${MC_USER}
      MC_PW: ${MC_PW}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HONEYBADGER_API_KEY_MANAGEMENT: ${HONEYBADGER_API_KEY_MANAGEMENT}
      POSTGRES_DB: management_yul_production
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      S3_SOURCE_BUCKET_NAME:
      SAMPLE_BUCKET:
      SOLR_BASE_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management_worker
