version: '3'
services:
  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    environment:
      HTTP_USERNAME: ${HTTP_USERNAME}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HONEYBADGER_API_KEY: ${HONEYBADGER_API_KEY_MANAGEMENT}
      POSTGRES_DB: management_yul_production
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      SOLR_BASE_URL: http://${CLUSTER_NAME}-solr.local:8983/solr
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.local
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management
