version: '3'
services:
  management:
    image: yalelibraryit/dc-management:${MANAGEMENT_VERSION}
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
      PASSENGER_APP_ENV: development # development
      POSTGRES_DB: management_yul_development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_RELATIVE_URL_ROOT: /management
      SAMPLE_BUCKET: yul-development-samples
      SOLR_BASE_URL: http://solr:8983/solr
      SOLR_CORE: blacklight-core
      VPN:
    ports:
      - "3001:3001"
