version: '3'
services:
  management:
    <%- if in_management? -%>
    build: .
    image: yalelibraryit/dc-management:master
    <%- end -%>
    environment:
      ACCESS_MASTER_MOUNT: "s3" # The path to the mounted drive, or "S3"
      BLACKLIGHT_BASE_URL: "http://localhost:3000"
      GOOBI_MOUNT: "data"
      IIIF_IMAGE_BASE_URL: "http://localhost:8182/iiif"
      IIIF_MANIFESTS_BASE_URL: "http://localhost/manifests/"
      PDF_BASE_URL: "http://localhost/pdfs/"
      PASSENGER_APP_ENV: ${PASSENGER_APP_ENV:-development}
      POSTGRES_MULTIPLE_DATABASES: management_yul_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SAMPLE_BUCKET: yul-dc-development-samples # manifests
      S3_SOURCE_BUCKET_NAME: yul-dc-dev-image-samples # image and ptiffs
      SOLR_TEST_CORE: blacklight-test
      LD_PRELOAD: ""
    <%- if in_management? -%>
    volumes:
      - .:/home/app/webapp:cached
      - management_node_modules:/home/app/webapp/node_modules
      - management_rails_cache:/home/app/webapp/tmp/cache
    <%- end -%>
    stdin_open: true
    tty: true
    depends_on:
      <%- unless without.match(/db/) -%>
      - db
      <%- end -%>
      <%- unless without.match(/solr/) -%>
      - solr
      <%- end -%>
      - management_worker
