version: '3'
services:
  solr:
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: solr
    volumes:
      - solr_efs:/var/solr/data/blacklight-core #this appears to not support variable expansion :/
    command: /bin/bash -c '/boot.sh'
    environment:
      SOLR_CORE: blacklight-core
      DYNATRACE_TOKEN: ${DYNATRACE_TOKEN}
      CLUSTER_NAME: ${CLUSTER_NAME}

volumes:
  solr_efs:
