version: '3'
services:
  management_worker:
    <%- if in_management? -%>
    build: .
    image: yalelibraryit/dc-management:master
    <%- end -%>
    environment:
      ACCESS_MASTER_MOUNT: "s3" # The path to the mounted drive, or "S3"
      # Use AWS credentials for local development only
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BLACKLIGHT_BASE_URL: "http://localhost:3000"
      IIIF_IMAGE_BASE_URL: "http://localhost:8182/iiif"
      IIIF_MANIFESTS_BASE_URL: "http://localhost/manifests/"
      PASSENGER_APP_ENV: development
      POSTGRES_MULTIPLE_DATABASES: management_yul_development
      SOLR_TEST_CORE: blacklight-test
    <%- if in_management? -%>
    volumes:
      - .:/home/app/webapp:cached
      - management_node_modules:/home/app/webapp/node_modules
      - management_rails_cache:/home/app/webapp/tmp/cache
    <%- end -%>
    depends_on:
      <%- unless without.match(/db/) -%>
      - db
      <%- end -%>
      <%- unless without.match(/solr/) -%>
      - solr
      <%- end -%>

<%- if in_management? -%>
volumes:
  management_node_modules:
  management_rails_cache:
<%- end %>
