version: '3'
services:
  management_worker:
    environment:
      AWS_ACCESS_KEY_ID: ${DEPLOY_KEY_ID}
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${DEPLOY_ACCESS_KEY}
      GOOBI_MOUNT:
      GOOBI_SCAN_DIRECTORIES:
      HTTP_USERNAME: ${HTTP_USERNAME}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
      IIIF_IMAGE_BASE_URL:
      IIIF_MANIFESTS_BASE_URL:
      PDF_BASE_URL:
      MC_USER: ${MC_USER}
      MC_PW: ${MC_PW}
      METADATA_CLOUD_HOST:
      ACCESS_MASTER_MOUNT: "/data" # The path to the mounted drive, or "s3"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      HONEYBADGER_API_KEY_MANAGEMENT: ${HONEYBADGER_API_KEY_MANAGEMENT}
      POSTGRES_DB: management_yul_production
      PASSENGER_APP_ENV: ${RAILS_ENV:-production}
      RAILS_ENV: ${RAILS_ENV:-production}
      S3_SOURCE_BUCKET_NAME:
      ACCESS_DOWNLOAD_BUCKET:
      OCR_DOWNLOAD_BUCKET:
      SAMPLE_BUCKET:
      SOLR_BASE_URL: http://${CLUSTER_NAME}-solr.${CLUSTER_NAME}:8983/solr
      POSTGRES_HOST: ${CLUSTER_NAME}-psql.${CLUSTER_NAME}
    volumes:
      - /brbl-dsu:/brbl-dsu
      - /data:/data
    logging:
      driver: awslogs
      options:
        awslogs-group: ${CLUSTER_NAME}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: management_worker
